const modal=document.getElementById('modal');
const title=document.getElementById('modal-title');
const type=document.getElementById('modal-type');
const cv=document.getElementById('modal-cv');

const layouts={
 executive:`<div class="modal-spread"><div class="modal-page"><small>EXECUTIVE CURRICULUM VITAE · 2026</small><h3>Alexander<br><i style="color:#a07b48">Laurent</i></h3><p style="letter-spacing:.12em;font-size:8px">CREATIVE DIRECTOR / BRAND STRATEGIST</p><div class="fake-line"></div><div class="fake-grid"><div><small>PROFILE</small><p>Creative leader with 9+ years building premium identities, campaigns and high-performing teams. Combines commercial strategy with a strong editorial eye.</p><small>CORE EXPERTISE</small><div class="tags"><span>Brand Strategy</span><span>Creative Direction</span><span>Leadership</span><span>Campaign Systems</span></div></div><div><small>CONTACT</small><p>Paris · London<br>alex.laurent@email.com<br>+33 6 12 34 56 78</p><small>LANGUAGES</small><p>French — Native<br>English — Fluent<br>Italian — Professional</p></div></div><div style="position:absolute;bottom:35px;left:42px;right:42px;border-top:1px solid #d4ccbf;padding-top:10px;font-size:7px;color:#8b8377">GILDED QUILL STUDIO · PRACTICE CLIENT</div></div><div class="modal-page"><small>EXPERIENCE / SELECTED IMPACT</small><h3 style="font-size:42px">Career<br><i style="color:#a07b48">Highlights</i></h3><div class="timeline"><article><b>MAISON STUDIO — CREATIVE DIRECTOR</b><span>Paris · 2019 — Present</span><p>Lead a multidisciplinary team across identity, campaigns and digital. Directed 30+ launches for fashion, hospitality and technology clients.</p></article><article><b>ATELIER NORTH — SENIOR BRAND LEAD</b><span>London · 2016 — 2019</span><p>Built brand frameworks and campaign systems for international consumer brands, improving consistency across 18 markets.</p></article><article><b>FORM &amp; CO. — BRAND DESIGNER</b><span>Paris · 2014 — 2016</span><p>Designed identities, packaging and campaign toolkits for emerging premium brands.</p></article></div><div class="fake-line"></div><div class="fake-grid"><div><small>EDUCATION</small><p><strong>ESCP Business School</strong><br>MA, Brand Management<br>2012 — 2014</p></div><div><small>SELECTED RESULTS</small><p><strong>30+</strong> launches<br><strong>18</strong> global markets<br><strong>9+</strong> years experience</p></div></div></div></div>`,
 editorial:`<div class="modal-spread"><div class="modal-page dark"><small style="color:#b18a50">THE CREATIVE EDITION · 02</small><h3>Olivia<br><i style="color:#c6a36a">Moreau</i></h3><p style="letter-spacing:.13em;font-size:8px">CREATIVE DIRECTOR / VISUAL STORYTELLER</p><div class="fake-line"></div><div class="fake-grid"><div><small>PROFILE</small><p>Visual storyteller with 8 years across fashion, culture and digital. Builds identities that feel distinctive in a room and coherent across every touchpoint.</p><small>SELECTED WORK</small><p>Maison Culture<br>Vogue House<br>Atelier No. 7<br>Form / Studio</p></div><div><small>CONTACT</small><p>Paris · New York<br>olivia.moreau@email.com<br>@oliviamoreau</p><small>DISCIPLINES</small><div class="tags"><span>Art Direction</span><span>Editorial</span><span>Campaigns</span><span>Identity</span></div></div></div><div style="position:absolute;bottom:35px;left:42px;right:42px;border-top:1px solid #4a4338;padding-top:10px;font-size:7px;color:#8f897f">CREATIVE PRACTICE CONCEPT · ORIGINAL GILDED QUILL DESIGN</div></div><div class="modal-page dark"><small style="color:#b18a50">01 — EXPERIENCE</small><h3 style="font-size:42px">Selected<br><i style="color:#c6a36a">Work</i></h3><div class="timeline"><article><b>MAISON CULTURE — CREATIVE DIRECTOR</b><span>Paris / New York · 2021 — Present</span><p>Creative direction for cultural campaigns, editorial launches and brand partnerships across two markets.</p></article><article><b>VOGUE HOUSE — ART DIRECTOR</b><span>Paris · 2018 — 2021</span><p>Designed visual systems for editorial features, events and digital storytelling.</p></article><article><b>STUDIO NO. 7 — DESIGNER</b><span>London · 2016 — 2018</span><p>Developed identities and campaign assets for fashion and hospitality clients.</p></article></div><div class="fake-line"></div><small style="color:#b18a50">CAPABILITIES</small><div class="tags" style="margin-top:10px"><span>Visual Identity</span><span>Creative Strategy</span><span>Art Direction</span><span>Photography</span><span>Editorial Design</span><span>Campaign Systems</span></div></div></div>`,
 modern:`<div class="modal-spread"><div class="modal-page modern"><small>PRODUCT DESIGN · UX · SYSTEMS</small><h3 style="font-family:Manrope,sans-serif;font-weight:700">Daniel<br>Kim</h3><p style="font-size:9px;letter-spacing:.08em">PRODUCT DESIGN LEAD</p><div class="fake-line"></div><div class="fake-grid"><div><small>ABOUT</small><p>Product designer focused on turning complex systems into clear digital experiences.</p><small>CONTACT</small><p>San Francisco, CA<br>daniel.kim@email.com<br>linkedin.com/in/danielkim</p></div><div><small>SKILLS</small><div class="tags"><span>Product Strategy</span><span>UX Research</span><span>Design Systems</span><span>Prototyping</span><span>Figma</span></div></div></div><div style="position:absolute;bottom:35px;left:42px;right:42px;border-top:1px solid #c2c7c1;padding-top:10px;font-size:7px;color:#777d76">GILDED QUILL STUDIO · PRACTICE CLIENT</div></div><div class="modal-page modern"><small>EXPERIENCE / SELECTED RESULTS</small><h3 style="font-family:Manrope,sans-serif;font-size:42px;font-weight:700">Systems<br>that <i style="font-family:Playfair Display;color:#a07b48">scale.</i></h3><div class="timeline"><article><b>NORTHLINE — LEAD PRODUCT DESIGNER</b><span>2020 — Present</span><p>Own product direction across a B2B platform used by 40k+ professionals. Introduced a scalable design system that reduced interface inconsistencies by 62%.</p></article><article><b>FORMA LABS — PRODUCT DESIGNER</b><span>2018 — 2020</span><p>Led discovery, interaction design and prototyping for mobile and web products from concept to launch.</p></article><article><b>EDUCATION</b><span>Stanford University · MS Product Design · 2016 — 2018</span><p>Focus: human-centered systems, interaction and digital product strategy.</p></article></div><div class="fake-line"></div><div class="fake-grid"><div><small>40K+</small><p>active users</p></div><div><small>62%</small><p>fewer UI inconsistencies</p></div></div></div></div>`
};

document.querySelectorAll('.project').forEach(project=>project.querySelector('.view-btn').addEventListener('click',()=>{
  title.textContent=project.dataset.title;
  type.textContent=project.dataset.type+' · Complete 2-page concept';
  cv.innerHTML=layouts[project.dataset.style];
  modal.classList.add('open');
}));

document.querySelector('.close').onclick=()=>modal.classList.remove('open');
modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
